### ISSUE TITLE
Roadmap to version 3.0

### ISSUE THREAD

**Issue by llaville** [llaville/php-reflect#13]
If you want to have more feature than currently existing in branch 2, don't hesitate to open a request here.
If it's accepted, it will be included in this roadmap.

# Next major release

## alpha-1
*due date 2014-12-22*

- [x] improve analysis speed. See issue #9 
- [x] reduce memory consumption. See issue #9
- [x] ability to provide a file or a directory in command line, without to specify it in `phpreflect.json` config file
- [x] use Symfony Component 2.5 or better
- [x] replace Symfony Console `TableHelper`, by `Table` helper (Ready for Symfony 3) 
- [x] replace Symfony Console `ProgressHelper`, by `ProgressBar` helper (Ready for Symfony 3) 
- [x] remove old component `ProviderManager`, and used instead directly a Symfony `Finder` instance 
- [x] ability to disable all plugins with option `--no-plugins` (ala Composer)
- [x] add a `PluginManager` to handle all plugins with configuration and the programmation
- [x] Similar API with other SAPI than the CLI version 
- [x] Write CLI result to file or URL (E.g: FTP)

## alpha-2
*due date 2015-01-05*

Stabilize and synchronize with CompatInfo 4.0 alpha-2

## alpha-3
*due date 2015-01-15*

Last alpha version, before stabilization of final API 3.0
- [x]  checking pre-conditions before traversing AST

## stable
*in 2015 but no due date*

- [x] full documentation available
 - [x] a user guide
 - [x] a developer guide
 - [x] a migration guide
- [x] full unit tests passing

**Comment by llaville** [comment]
Reflect 3.0.0-alpha2 has just been released. Learn more on [blog](http://php5.laurent-laville.org/reflect/blog/201501-Reflect-3.0-alpha-2.html)

**Comment by llaville** [comment]
Reflect 3.0.0-alpha3 has just been released. Learn more on [blog](http://php5.laurent-laville.org/reflect/blog/)

**Comment by llaville** [comment]
Reflect 3.0.0-beta1 has just been released. Learn more on [blog](http://php5.laurent-laville.org/reflect/blog/)

Only the User Guide was updated to major version 3. Other guides will follow in next days !

**Comment by llaville** [comment]
Reflect 3.0.0-beta3 has just been released. Learn more on [blog](http://php5.laurent-laville.org/reflect/blog/)
