### ISSUE TITLE
ROADMAP-v5

### ISSUE THREAD

**Issue by llaville** [llaville/php-reflect#31]
- [X] version 5.0.0-alpha1 : january 20
- [X] version 5.0.0-alpha2 :  february 3
- [X] version 5.0.0-alpha3 :  april 7
- [X] version 5.0.0-beta1 :  april 13
- [ ] version 5.0.0-RC1 : february 2 - delayed
- [ ] version 5.0.0 stable : february 15 - delayed

This roadmap is able to be modified, depending of feedback and tests run by all contributors and/or users.

**Comment by llaville** [comment]
Core code with all features of v5.0 are now ready for production.

Last Alpha version have just been published. Unit Tests and Docs need to be fixed now before going to beta or RC versions.

**Comment by llaville** [comment]
Code is now stabilized with first beta.
Remaining is to migrate doc from asciidoc to markdown format before going to RC and stable versions.

**Comment by llaville** [comment]
Code of branch v5 is outdated and should be either removed or fixed (but I don't know when).
Code should be rebase on branch 4.4

**Comment by llaville** [comment]
Major version 5.0 is cancelled.
PHP Reflect reached end-of-life with version 4.4.0
