### ISSUE TITLE
ROADMAP-v4

### ISSUE THREAD

**Issue by llaville** [llaville/php-reflect#38]
About version 4.4, the last of branch v4

- [X] drop support to PHP 5
- [X] drop support to Symfony 2 and 3, and allows only Symfony 4 LTS and Symfony 5
- [X] drop support to `sebastian/version` v1
- [X] raise `phpdocumentor/reflection-docblock` constraint to v4.3
- [X] raise `justinrainbow/json-schema` constraint to v5.2
- [X] raise `seld/jsonlint` constraint to v1.4
- [X] upgrade `nikic/php-parser` to v4.5
- [X] [Simpler event dispatching](https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching) available since Symfony 4.3

**Comment by llaville** [comment]
A really cool article about event dispatching : [The Bulletproof Event Naming For Symfony Event Dispatcher](https://tomasvotruba.com/blog/2020/05/25/the-bulletproof-event-naming-for-symfony-event-dispatcher/)

**Comment by llaville** [comment]
@remicollet Pre-condition to my ROADMAP (publish new version 5.3.0 of PHP_CompatInfo : see https://github.com/llaville/php-compatinfo-db/issues/47) is over.
I've just finished to commit all changes of upcoming version 4.4.0 of PHP_Reflect (that will be used by CompatInfo 5.3) in branch [4.4](https://github.com/llaville/php-reflect/tree/4.4)
If you've time to have a look on it before to release it officially, I'll glad !

**Comment by remicollet** [comment]
Can you please consider allowing phpdocumentor/type-resolver  `"phpdocumentor/type-resolver": "~0.4 || ^1.0.0",`
to be in sync with what required by `phpdocumentor/reflection-docblock`

Notice, test suite passes with both **0.4** and **1.3.0** (which are the versions available in Fedora)

**Comment by llaville** [comment]
Push [fix](https://github.com/llaville/php-reflect/commit/23697aa21ff84194d96727f4b0ed4f11895e0a16) to be compatible SF 4.4 and 5.x about EventDispatcherInterface

**Comment by remicollet** [comment]
Using latest commit (in 4.4), everything seems OK, test suite passes, and `phpcompatinfo` command works (some basic analysis)

**Comment by llaville** [comment]
I'm still looking at phpcompatinfo, because I see warning with PHP 7.4 and Symfony 5.1

```
Warning: Declaration of Bartlett\Reflect\Console\Application::setDispatcher(Symfony\Component\EventDispatcher\EventDispatcherInterface $dispatcher): void should be compatible with Symfony\Component\Console\Application::setDispatcher(Sym
fony\Contracts\EventDispatcher\EventDispatcherInterface $dispatcher) in /shared/backups/bartlett/php-compat-info/vendor/bartlett/php-reflect/src/Bartlett/Reflect/Console/Application.php on line 116

```

With SF 4.4 all seems ok (for me)

**Comment by llaville** [comment]
Last [commit](https://github.com/llaville/php-reflect/commit/a7f59ab84e44f34d0896bb6be64b9442bc39b94d) to solve conflict with SF 4.4 and 5.x
I'll publish the official and final version 4.4.0 tomorrow

**Comment by llaville** [comment]
Final version 4.4.0 has just been released !
